# Generated by Django 5.2.3 on 2025-06-23 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('cod_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('nome_cargo', models.CharField(max_length=25)),
                ('salario_cargo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Hospede',
            fields=[
                ('cod_hospede', models.AutoField(primary_key=True, serialize=False)),
                ('nome_hospede', models.CharField(max_length=50)),
                ('sobrenome_hospede', models.CharField(max_length=50)),
                ('email_hospede', models.EmailField(max_length=200)),
                ('senha_hospede', models.CharField(max_length=50)),
                ('cpf_hospede', models.CharField(max_length=11)),
                ('telefone_hospede', models.CharField(max_length=15)),
                ('data_nascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Quartos',
            fields=[
                ('cod_quarto', models.AutoField(primary_key=True, serialize=False)),
                ('camas', models.IntegerField()),
                ('disponibilidade', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_quarto',
            fields=[
                ('cod_tipo_quarto', models.AutoField(primary_key=True, serialize=False)),
                ('nome_tipo', models.CharField(max_length=20)),
                ('preco_tipo', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('cod_turno', models.AutoField(primary_key=True, serialize=False)),
                ('nome_turno', models.CharField(max_length=10)),
                ('inicio_turno', models.TimeField()),
                ('termino_turno', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('cod_funcionario', models.AutoField(primary_key=True, serialize=False)),
                ('nome_funcionario', models.CharField(max_length=50)),
                ('sobrenome_funcionario', models.CharField(max_length=50)),
                ('cpf_funcionario', models.CharField(max_length=11)),
                ('email_funcionario', models.EmailField(max_length=200)),
                ('telefone_funcionario', models.CharField(max_length=15)),
                ('cod_cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotelaria.cargos')),
                ('cod_turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotelaria.turno')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('cod_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('cancelada', 'Cancelada'), ('finalizada', 'Finalizada')], max_length=10)),
                ('cod_hospede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelaria.hospede')),
                ('cod_quarto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotelaria.quartos')),
            ],
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('cod_servico', models.AutoField(primary_key=True, serialize=False)),
                ('nome_servico', models.CharField(max_length=30)),
                ('preco_servico_adicional', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cod_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotelaria.funcionarios')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva_Servicos',
            fields=[
                ('cod_servico_acionado', models.AutoField(primary_key=True, serialize=False)),
                ('cod_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelaria.reserva')),
                ('cod_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelaria.servicos')),
            ],
        ),
        migrations.AddField(
            model_name='quartos',
            name='tipo_quarto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotelaria.tipo_quarto'),
        ),
    ]
